name: Frontend_classroom

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy Frontend_classroom
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # âœ… Install PNPM if not installed
      - name: Ensure PNPM is installed
        run: |
          if ! command -v pnpm &> /dev/null; then
            npm install -g pnpm
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Replace .env with .env.production
        run: cp -f .env.production .env

      - name: Production build
        run: NEXT_PUBLIC_ENV=production pnpm build

      - name: Start/Restart frontend_classroom with PM2
        run: |
          if pm2 list | grep -q "frontend_classroom"; then
            pm2 restart frontend_classroom
          else
            pm2 start pnpm --name "frontend_classroom" -- start
          fi
